apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:  
      containers:
      - name: clientcont
        image: shivrajpatil1998/frontend7
        ports:
        - containerPort: 3000
        tty: true
        env:
            - name: REACT_APP_API_URL
              value: http://192.168.49.2:32691

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  selector:
    app: client 
  type: NodePort  
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000  
